INSERT INTO ingredients (ing_name, volume, manufacturer_name, manufacturer_address, price, provider_id)
VALUES ('coffee', '1kg', 'Coffeeeeee Co.', 'Light Street 333', 2000, 3),
			 ('green tea', '1kg', 'Tea Leaf Imports', 'Roobergs Street J89', 5100, 3),
			 ('black tea', '1kg', 'Tea Leaf Imports', 'Roobergs Street J89', 4800, 3),
			 ('matcha tea', '1kg', 'Tea Leaf Imports', 'Roobergs Street J89', 10000, 3),
			 ('milk', '1L', 'Flavour Fusion Co.', 'Qoot Square 8', 150, 4),
			 ('coconut milk', '1L', 'Flavour Fusion Co.', 'Qoot Square 8', 300, 4),
			 ('banana milk', '1L', 'Flavour Fusion Co.', 'Qoot Square 8', 350, 4),
			 ('cream', '1L', 'Flavour Fusion Co.', 'Qoot Square 8', 800, 4),
			 ('ice cream', '1kg', 'Flavour Fusion Co.', 'Qoot Square 8', 800, 4),
			 ('chocolate', '1bar', 'Choco World', 'King Star Street 5098', 150, 5),
			 ('peach juice', '1L', 'All Juice', 'Kotton Avenue 90', 160, 5),
			 ('cola', '0,3L', 'Drinks For Everyone', 'Mango Boulevard 7347', 200, 5),
			 ('still water', '0,3L', 'Drinks For Everyone', 'Mango Boulevard 7347', 80, 5),
			 ('sparkling water', '0,3L', 'Drinks For Everyone', 'Mango Boulevard 7347', 80, 5),
			 ('vanilla syrup', '1L', 'Caramel Madness Merchants', 'Candy Avenue 67', 600, 6),
			 ('caramel syrup', '1L', 'Caramel Madness Merchants', 'Candy Avenue 67', 600, 6),
			 ('lavander syrup', '1L', 'Caramel Madness Merchants', 'Candy Avenue 67', 600, 6),
			 ('passion fruit syrup', '1L', 'Caramel Madness Merchants', 'Candy Avenue 67', 600, 6),
			 ('mint', '100g', 'Exotic Blend Merchants', 'Tasty Street 123', 400, 7),
			 ('orange', '1kg', 'Exotic Blend Merchants', 'Tasty Street 123', 300, 7),
			 ('lemon', '1kg', 'Exotic Blend Merchants', 'Tasty Street 123', 400, 7),
			 ('berry mix', '1kg', 'Exotic Blend Merchants', 'Tasty Street 123', 700, 7),
			 ('banana', '1kg', 'Exotic Blend Merchants', 'Tasty Street 123', 300, 7);
			 --test